#YsoGUI local app state
#Tue May 05 14:11:29 CST 2026
lastDir=E\:\\tools\\YsoGUI\\lib
lastJar=E\:\\tools\\YsoGUI\\lib\\ysoserial-0.0.6-SNAPSHOT-all.jar
lastMarshalsec=E\:\\tools\\YsoGUI\\lib\\marshalsec-0.0.3-SNAPSHOT-all.jar
